### ISSUE TITLE
Error: "line" is not a registered controller.

### ISSUE THREAD

**Issue by uraden** [uraden/weather_app#1]
I created a React app which works fine in my local machine. But after deploying it to Github I am getting following error msg

`Error: "line" is not a registered controller.`

I have tried many solutions which I found on Stackoverflow and GitHub, but none of them worked for me.
Can someone assist me with this issue. 

Thanks

**Comment by tinohager** [comment]
Maybe this help, add `LineController`

https://github.com/uraden/weather_app/blob/03e24eebfb34da8dfc8d615e2b4140ff59738de2/src/App.js#L9
```
import {
  Chart as ChartJS,
  LinearScale,
  CategoryScale,
  BarElement,
  PointElement,
  LineController
  LineElement,
  Legend,
  Tooltip,
  registerables as registerablesJS
} from "chart.js";
import { Chart} from "react-chartjs-2";
ChartJS.register(...registerablesJS);



ChartJS.register(
  LinearScale,
  CategoryScale,
  BarElement,
  PointElement,
  LineController 
  LineElement,
  Legend,
  Tooltip
);
```
